version: 0.2

env:
  git-credential-helper: yes

phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: latest
    commands:
      # Upgrade pip to the latest version
      - pip install --upgrade pip

      # Install requirements
      - pip install boto3

  build:
    commands:
      # Update layers for each lambda
      - python helper/pipeline/update_layers/update_lambdas.py
      # Call lambda function to update data
            # Run data update functions
      - aws lambda invoke --function-name detektivkollektiv-archive_api-update-warning-tags-${STAGE}

