AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM template for DetektivKollektiv API'

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  STAGE:
    Type: String

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: STAGE

  SearchFactChecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-SearchFactChecks-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: SearchFactChecks.get_FactChecks
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

  GetLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetLanguage-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: GetLanguage.get_language
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

  GetKeyPhrasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetKeyPhrases-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: GetKeyPhrases.get_phrases
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

GetEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetEntities-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: GetEntities.get_entities
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

ExtractClaimFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-ExtractClaim-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: ExtractClaim.extract_claim
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn

GetSentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetSentiment-${STAGE}'
      CodeUri: factcheck_searching/
      Handler: GetSentiment.get_sentiment
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
