"""Add warning tag to question table

Revision ID: 0b461ec72ef4
Revises: efd97d68c529
Create Date: 2021-09-02 14:46:54.730242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b461ec72ef4'
down_revision = 'efd97d68c529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_questions', sa.Column(
        'warning_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_questions', 'warning_tag')
    # ### end Alembic commands ###
