"""modified item_model to output tags sorted by counts

Revision ID: 1594a357d751
Revises: 4f46016acb9c
Create Date: 2021-05-04 10:44:25.692540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1594a357d751'
down_revision = '4f46016acb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_tags', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_tags', 'count')
    # ### end Alembic commands ###
