"""Added foreign keys for question_option_pairs

Revision ID: 1985fcb18803
Revises: f12721104288
Create Date: 2021-03-31 09:15:23.599529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1985fcb18803'
down_revision = 'f12721104288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_option_pairs_ibfk_1', 'question_option_pairs', type_='foreignkey')
    op.drop_constraint('question_option_pairs_ibfk_2', 'question_option_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'question_option_pairs', 'review_questions', ['question_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'question_option_pairs', 'answer_options', ['option_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_option_pairs', type_='foreignkey')
    op.drop_constraint(None, 'question_option_pairs', type_='foreignkey')
    op.create_foreign_key('question_option_pairs_ibfk_2', 'question_option_pairs', 'review_questions', ['question_id'], ['id'])
    op.create_foreign_key('question_option_pairs_ibfk_1', 'question_option_pairs', 'answer_options', ['option_id'], ['id'])
    # ### end Alembic commands ###
