"""item_types

Revision ID: 310dab6e8966
Revises: 7e1207d1a7e1
Create Date: 2021-01-08 22:02:15.698965

"""

import json
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '310dab6e8966'
down_revision = '7e1207d1a7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_types',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('answer_options', sa.Column(
        'tooltip', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('item_type_id',
                                     sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_items_item_type_id', 'items', 'item_types', [
                          'item_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('review_questions', sa.Column(
        'hint', sa.Text(), nullable=True))
    op.add_column('review_questions', sa.Column(
        'item_type_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_review_questions_item_type_id', 'review_questions', 'item_types', ['item_type_id'], [
                          'id'], onupdate='CASCADE', ondelete='CASCADE')

    item_types_table = sa.table(
        'item_types',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.Text(), nullable=True)
    )

    with open(f'./alembic/data/{revision}/item_types.json', 'r', encoding='utf8') as item_types_file:
        data = item_types_file.read()

    item_types = json.loads(data)

    op.bulk_insert(item_types_table, item_types)
    op.execute(
        "UPDATE items SET item_type_id=(SELECT id FROM item_types WHERE item_types.name=items.type)")

    # Answer Options

    op.execute("DELETE question_option_pairs FROM question_option_pairs")
    op.execute("DELETE answer_options FROM answer_options")

    options_table = sa.table(
        'answer_options',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('text', sa.Text(), nullable=True),
        sa.Column('value', sa.Integer(), nullable=True),
        sa.Column('tooltip', sa.Text(), nullable=True)
    )

    with open(f'./alembic/data/{revision}/answer_options.json', 'r', encoding='utf8') as answer_options_file:
        data = answer_options_file.read()

    options = json.loads(data)

    op.bulk_insert(options_table, options)

    # Questions

    op.execute("DELETE review_questions FROM review_questions")

    questions_table = sa.table(
        'review_questions',
        sa.Column('id', sa.String(36)),
        sa.Column('content', sa.Text()),
        sa.Column('info', sa.Text()),
        sa.Column('hint', sa.Text()),
        sa.Column('item_type_id', sa.String(36)),
        sa.Column('max_children', sa.Integer()),
        sa.Column('parent_question_id', sa.String(36)),
        sa.Column('lower_bound', sa.Integer()),
        sa.Column('upper_bound', sa.Integer())
    )

    with open(f'./alembic/data/{revision}/review_questions.json', 'r', encoding='utf8') as questions_file:
        data = questions_file.read()

    questions = json.loads(data)

    op.bulk_insert(questions_table, questions)

    # Question Option Pairs

    op.execute("DELETE question_option_pairs FROM question_option_pairs")

    question_option_pairs_table = sa.table(
        'question_option_pairs',
        sa.Column('question_id', sa.String(36)),
        sa.Column('option_id', sa.String(36))
    )

    with open(f'./alembic/data/{revision}/question_option_pairs.json', 'r', encoding='utf8') as question_option_pairs_file:
        data = question_option_pairs_file.read()

    question_option_pairs = json.loads(data)

    op.bulk_insert(question_option_pairs_table, question_option_pairs)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_review_questions_item_type_id',
                       'review_questions', type_='foreignkey')
    op.drop_column('review_questions', 'item_type_id')
    op.drop_column('review_questions', 'hint')
    op.drop_constraint('fk_items_item_type_id', 'items', type_='foreignkey')
    op.drop_column('items', 'item_type_id')
    op.drop_column('answer_options', 'tooltip')
    op.drop_table('item_types')
    # ### end Alembic commands ###
