"""Verification process 2.0

Revision ID: 3dfcec659fd7
Revises: 6bfe320a60ad
Create Date: 2020-11-19 16:41:35.223568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dfcec659fd7'
down_revision = '6bfe320a60ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_pairs',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('item_id', sa.String(length=36), nullable=True),
                    sa.Column('junior_review_id', sa.String(
                        length=36), nullable=True),
                    sa.Column('senior_review_id', sa.String(
                        length=36), nullable=True),
                    sa.Column('is_good', sa.Boolean(), nullable=True),
                    sa.Column('variance', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
                    sa.ForeignKeyConstraint(
                        ['junior_review_id'], ['reviews.id'], ),
                    sa.ForeignKeyConstraint(
                        ['senior_review_id'], ['reviews.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.add_column('items', sa.Column(
        'verification_process_version', sa.Integer(), nullable=True))
    op.drop_constraint('review_answers_ibfk_1',
                       'review_answers', type_='foreignkey')
    op.create_foreign_key(None, 'review_answers', 'reviews', ['review_id'], [
                          'id'], onupdate='CASCADE', ondelete='CASCADE')

    op.add_column('review_questions', sa.Column(
        'lower_bound', sa.Integer(), nullable=True))
    op.add_column('review_questions', sa.Column(
        'max_children', sa.Integer(), nullable=True))
    op.add_column('review_questions', sa.Column(
        'parent_question_id', sa.String(length=36), nullable=True))
    op.add_column('review_questions', sa.Column(
        'upper_bound', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review_questions', 'review_questions', [
                          'parent_question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('review_questions', 'mandatory')

    op.drop_column('reviews', 'peer_review_id')
    op.drop_constraint('reviews_ibfk_1', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'items', ['item_id'], [
                          'id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###

    # mark closed items
    op.execute(
        'UPDATE items SET verification_process_version = 1 WHERE status = "closed"')
    # reset open items and delete reviews
    op.execute(
        'UPDATE items SET open_reviews = 4, open_reviews_level_1 = 4, open_reviews_level_2 = 4, in_progress_reviews_level_1 = 0, in_progress_reviews_level_2 = 0 WHERE status = "open"')
    op.execute(
        'DELETE reviews FROM reviews INNER JOIN items on reviews.item_id = items.id WHERE items.status = "open"')

    # Update/Insert review questions with parent ids, bounds and children columns
    op.execute('INSERT INTO review_questions (id, content, info, parent_question_id, lower_bound, upper_bound, max_children) \
        VALUES \
        ("1", "Im Artikel/der Nachricht werden für alle Behauptungen/Thesen Originalquellen genannt.", "Erklärung: Die Angabe von Quellen für Zitate oder Behauptungen erhöht die Glaubwürdigkeit der in Artikeln/Texten aufgestellten Thesen.", NULL, NULL, NULL, 1), \
        ("1a", "Der Inhalt des Artikels/der Nachricht deckt sich vollständig mit dem der Originalquelle/n.", NULL, "1", 3, 4, NULL), \
        ("1b", "Recherchiere die Originalquelle. Der Inhalt des Artikels/der Nachricht deckt sich vollständig mit dem der Originalquelle/n.", "Tipp: Suche nach der exakten Überschrift des Artikels/Textes in Suchmaschinen wie Google oder Ecosia, indem Du Anführungszeichen benutzt, um die Originalquelle zu finden. Beispiel: \'COVID-19 – Die Todesrate steigt.\'", "1", 1, 2, NULL), \
        ("2", "Die Grammatik und Rechtschreibung des Artikels/der Nachricht ist einwandfrei.", "Erklärung: Artikel/Nachrichten werden teils wörtich über Google Translate in gewünschte Sprachen übersetzt, um Informationen schnell zu zirkulieren ohne diese Inhalte vorab auf ihre Genauigkeit oder Korrektheit zu überprüfen. Fehlerhafte Grammatik, oder auch unlogischer Syntax können ein Indiz hierfür sein.", NULL, NULL, NULL, 0), \
        ("3", "Die Medien (Fotos, Bilder, Videos) im Artikel/in der Nachricht sind echt, stimmen im Kontext und sind zum angegeben Zeitpunkt entstanden/bilden ein Geschehen im angegebenen Zeitpunkt ab.", "Erklärung: Teils werden veraltete oder aus anderen Kontexten stammende Fotos, Bilder, Videos für Artikel/Nachrichten genutzt, um falsche Behauptungen glaubwürdiger erscheinen zu lassen. \n Tipp: Nutze Reverse Image Search, um zu sehen, ob Fotos in Artikeln/Nachrichten echt sind und nicht aus anderen Kontexten gegriffen sind. Hier ein Tool dafür: https://tineye.com/.", NULL, NULL, NULL, 0), \
        ("4", "Der Internetauftritt (URL Adresse, Logo, Design) des Mediums imitiert keine bereits bekannten Websites und Medien. Dies gilt auch für den Internetauftritt von Medien, deren Links in Nachrichten eingebettet sind.", "Tipp: Achte auf die gesamte Internetadresse (URL). Manche Webseiten imitieren bereits bekannte Medien. Beispiel: ABCnews.com vs. ABCnews.com.co \n Achte bei Artikeln auf die Qualität des Logos der Webseite und das Designs des Mediums.", NULL, NULL, NULL, 0), \
        ("5", "Der Inhalt des Artikels/der Nachricht deckt sich vollständig mit dem in der Überschrift suggerierten Inhalt.", NULL, NULL, NULL, NULL, 0), \
        ("6", "Der Inhalt des Artikels/der Nachricht deckt sich mit der Berichterstattung öffentlich/rechtlicher Medien und/oder Fachmedien.", NULL, NULL, NULL, NULL, 0), \
        ("7", "Im Artikel/der Nachricht werden Zitate zur Unterstützung des Inhalts und verschiedener Positionen als zusätzliche Quelle wiedergegeben.", "Erklärung: Manchmal werden Zitate nur für eine Seite wiedergegeben, was die Leserschaft indirekt dazu verleitet, einer Seite mehr Expertise zuzuschreiben.", NULL, NULL, NULL, 2), \
        ("7a", "Zitierte Personen im Artikel/in der Nachricht haben tatsächlich im vom Artikel/der Nachricht aufgegriffenen Thema Expertise und werden berechtigterweise als Quelle genuzt.", "Erklärung: Expert*in muss nicht bedeuten, dass die Person auch im gegeben, speziellen Thema Expertise besitzt. Bsp.: Krankenpfleger haben nicht dieselbe Expertise wie Virologen im Bereich der Epidemologie.", "7", 2, 4, NULL), \
        ("7b", "Die im Artikel/in der Nachricht verwendeten Zitate stimmen mit ihrem ursprünglichen Kontext überein und wurden nicht zweckentfremdet.", "Erklärung: Manchmal werden Zitate woanders aufgegriffen und womöglich in einem anderen Kontext gebraucht. Ebenso ist es möglich, dass Zitate gekürzt werden, um eine Aussage anders darzustellen.", "7", 2, 4, NULL), \
        ("8", "Das Medium scheint finanziell, politisch und thematisch unabhängig zu sein.", "Erklärung: Teils werden veraltete oder aus anderen Kontexten stammende Fotos, Bilder, Videos für Artikel/Nachrichten genutzt, um falsche Behauptungen glaubwürdiger erscheinen zu lassen. \n Tipp: Nutze Reverse Image Search, um zu sehen, ob Fotos in Artikeln/Nachrichten echt sind und nicht aus anderen Kontexten gegriffen sind. Hier ein Tool dafür: https://tineye.com/.", NULL, NULL, NULL, 0) \
        ON DUPLICATE KEY UPDATE \
        content=VALUES(content), \
        info = VALUES(info), \
        parent_question_id=VALUES(parent_question_id), \
        lower_bound=VALUES(lower_bound), \
        upper_bound=VALUES(upper_bound), \
        max_children=VALUES(max_children)')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('peer_review_id',
                                       mysql.VARCHAR(length=36), nullable=True))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_ibfk_1', 'reviews',
                          'items', ['item_id'], ['id'])
    op.add_column('review_questions', sa.Column('mandatory', mysql.TINYINT(
        display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'review_questions', type_='foreignkey')
    op.drop_column('review_questions', 'upper_bound')
    op.drop_column('review_questions', 'parent_question_id')
    op.drop_column('review_questions', 'max_children')
    op.drop_column('review_questions', 'lower_bound')
    op.drop_constraint(None, 'review_answers', type_='foreignkey')
    op.create_foreign_key('review_answers_ibfk_1',
                          'review_answers', 'reviews', ['review_id'], ['id'])
    op.drop_column('items', 'verification_process_version')
    op.drop_table('review_pairs')
    # ### end Alembic commands ###
