"""User timestamp added

Revision ID: 4e67ce1abb34
Revises: 310dab6e8966
Create Date: 2021-01-19 11:09:34.919424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e67ce1abb34'
down_revision = '310dab6e8966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sign_up_timestamp',
                                     sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE users SET sign_up_timestamp='2021-01-01 10:00:00'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sign_up_timestamp')
    # ### end Alembic commands ###
