"""Added ip adress column for submission and issue

Revision ID: 4f46016acb9c
Revises: 1985fcb18803
Create Date: 2021-03-31 17:21:18.888223

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f46016acb9c'
down_revision = '1985fcb18803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('ip_address', sa.String(length=15), nullable=True))
    op.add_column('submissions', sa.Column('ip_address', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'ip_address')
    op.drop_column('issues', 'ip_address')
    # ### end Alembic commands ###
