"""Added warning icon column to question table

Revision ID: 5777ebc2e120
Revises: 38c519f615c7
Create Date: 2021-10-20 14:24:11.647804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5777ebc2e120'
down_revision = '38c519f615c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_questions', sa.Column(
        'warning_tag_icon_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_questions', 'warning_tag_icon_code')
    # ### end Alembic commands ###
