"""Added Issue table

Revision ID: 73a447b63ffe
Revises: 9befe380e239
Create Date: 2021-02-11 16:57:23.386171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a447b63ffe'
down_revision = '9befe380e239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('category', sa.String(
                        length=100), nullable=False),
                    sa.Column('message', sa.String(
                        length=1000), nullable=False),
                    sa.Column('item_id', sa.String(length=36), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['item_id'], ['items.id'], onupdate='CASCADE', ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issues')
    # ### end Alembic commands ###
