"""Item defaults added

Revision ID: 8fea6624de3b
Revises: 73a447b63ffe
Create Date: 2021-02-25 16:05:42.185077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fea6624de3b'
down_revision = '73a447b63ffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'open_timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('users', 'sign_up_timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'sign_up_timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('items', 'open_timestamp',
               existing_type=mysql.DATETIME(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
