"""Added last question to Review

Revision ID: 9befe380e239
Revises: 69c8e4d86653
Create Date: 2021-02-10 10:29:00.020205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9befe380e239'
down_revision = '69c8e4d86653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('last_question_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'reviews', 'review_questions', ['last_question_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'last_question_id')
    # ### end Alembic commands ###
