"""create comment_model

Revision ID: ef75f333ea4a
Revises: 1594a357d751
Create Date: 2021-07-07 18:01:00.033671

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef75f333ea4a'
down_revision = '1594a357d751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('submission_id', sa.String(length=36), nullable=True),
    sa.Column('review_answer_id', sa.String(length=36), nullable=True),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['review_answer_id'], ['review_answers.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_sentiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('comment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('issues', sa.Column('comment_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'issues', 'comments', ['comment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'comment_id')
    op.drop_table('comment_sentiments')
    op.drop_table('comments')
    # ### end Alembic commands ###
