"""Implemented safe url feature

Revision ID: efd97d68c529
Revises: ef75f333ea4a
Create Date: 2021-08-16 08:07:28.074347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'efd97d68c529'
down_revision = 'ef75f333ea4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column(
        'unsafe', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'unsafe')
    # ### end Alembic commands ###
