"""Updated Reviewpair Foreign Keys

Revision ID: f12721104288
Revises: 8fea6624de3b
Create Date: 2021-02-25 19:03:09.226699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f12721104288'
down_revision = '8fea6624de3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_pairs_ibfk_3',
                       'review_pairs', type_='foreignkey')
    op.drop_constraint('review_pairs_ibfk_2',
                       'review_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'review_pairs', 'reviews', [
                          'junior_review_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'review_pairs', 'reviews', [
                          'senior_review_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_pairs', type_='foreignkey')
    op.drop_constraint(None, 'review_pairs', type_='foreignkey')
    op.create_foreign_key('review_pairs_ibfk_2', 'review_pairs', 'reviews', [
                          'junior_review_id'], ['id'])
    op.create_foreign_key('review_pairs_ibfk_3', 'review_pairs', 'reviews', [
                          'senior_review_id'], ['id'])
    # ### end Alembic commands ###
