"""Changed itemtag to include review id

Revision ID: f5a45e7f5473
Revises: 5777ebc2e120
Create Date: 2021-11-02 12:39:10.822508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5a45e7f5473'
down_revision = '5777ebc2e120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_tags', sa.Column(
        'review_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'item_tags', 'reviews', ['review_id'], ['id'])
    op.drop_column('item_tags', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_tags', sa.Column('count', mysql.INTEGER(
        display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_tags', type_='foreignkey')
    op.drop_column('item_tags', 'review_id')
    # ### end Alembic commands ###
