version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WhatsappForwarding"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17cicnw8tuz0u"
s3_prefix = "WhatsappForwarding"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

