AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM template for DetektivKollektiv API'

Globals:
  Function:
    Timeout: 30
Parameters:
  STAGE:
    Type: String
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: ${STAGE}

  WhatsappForwardingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-whatsapp_forwarding-${STAGE}'
      CodeUri: whatsapp_forwarding/
      Handler: app.whatsapp_forwarding
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        WhatsappForwarding:
          Type: Api
          Properties:
            Path: /whatsapp_forwarding
            Method: post
            RestApiId:
              Ref: Api
  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-create_item-${STAGE}'
      Handler: app.create_item
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items
            Method: post
            RestApiId:
              Ref: Api
  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-get_all_items-${STAGE}'
      Handler: app.get_all_items
      Runtime: python3.8
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items
            Method: get
            RestApiId:
              Ref: Api
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'detektivkollektiv-api-Execution${STAGE}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
