AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'SAM template for DetektivKollektiv API'

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.1
    
Parameters:
  STAGE:
    Type: String
  DBNAME:
    Type: String
    Default: development_db
    
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 
        Ref: STAGE

  WhatsappForwardingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-whatsapp_forwarding-${STAGE}'
      CodeUri: whatsapp_forwarding/
      Handler: app.whatsapp_forwarding
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        WhatsappForwarding:
          Type: Api
          Properties:
            Path: /whatsapp_forwarding
            Method: post
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  CreateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-create_item-${STAGE}'
      CodeUri: .
      Handler: app.create_item
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items
            Method: post
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  GetAllItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-get_all_items-${STAGE}'
      CodeUri: .
      Handler: app.get_all_items
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Tracing: Active
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items
            Method: get
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
              
  CreateSubmissionFunction:
    Type: AWS::Serverless::Function
    Properties:      
      FunctionName: !Sub 'detektivkollektiv-api-create_submission-${STAGE}'
      CodeUri: .
      Handler: app.create_submission
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /submissions
            Method: post
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  GetAllSubmissionsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-get_all_submissions-${STAGE}'
      CodeUri: .
      Handler: app.get_all_submissions
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submissions
            Method: get              
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  GetItemByContentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-get_item_by_content-${STAGE}'
      CodeUri: .
      Handler: app.get_item_by_content
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/byContent
            Method: post
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  SearchFactChecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-SearchFactChecks-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: SearchFactChecks.get_FactChecks
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetLanguage-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: GetLanguage.get_language
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetKeyPhrasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetKeyPhrases-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: GetKeyPhrases.get_phrases
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetEntities-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: GetEntities.get_entities
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  ExtractClaimFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-ExtractClaim-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: ExtractClaim.extract_claim
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetSentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-GetSentiment-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: GetSentiment.get_sentiment
      Runtime: python3.7
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  UpdateLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'detektivkollektiv-api-EnrichItem-${STAGE}'
      CodeUri: FactCheck_searching/
      Handler: EnrichItem.enrich_item
      Runtime: python3.7
      MemorySize: 832

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'detektivkollektiv-api-execution-${STAGE}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/ComprehendFullAccess
