AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 30
    
Parameters:
  Stage:
    Type: String

Resources:
  Api:
    Properties:
      StageName: ${STAGE}
    Type: AWS::Serverless::Api
    
  WhatsappForwardingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: whatsapp_forwarding/
      Handler: app.whatsapp_forwarding
      Runtime: python3.8
      Events:
        WhatsappForwarding:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /whatsapp_forwarding
            Method: post
            
  CreateItemFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app.create_item
      Runtime: python3.8
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items
            Method: post
            
  GetAllItemsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: app.get_all_items
      Runtime: python3.8
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/${STAGE}"
  WhatsappForwardingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt WhatsappForwardingFunction.Arn
  WhatsappForwardingIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt WhatsappForwardingFunctionRole.Arn
    
  CreateItemFunction:
    Description: "Lambda Function to create new item"
    Value: !GetAtt CreateItemFunction.Arn
    
  GetAllItemsFunction:
    Description: "Lambda Function to get all items"
    Value: !GetAtt GetAllItemsFunction.Arn