version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Upgrade pip to the latest version
      - pip install --upgrade pip

      # Install requirements
      - pip install alembic sqlalchemy mysqlclient

  build:
    commands:
      - cd lambda_layers/core_layer
      - alembic upgrade head
