version: 0.2

env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      python: 3.8
      ruby: latest
    commands:
      # Upgrade pip to the latest version
      - pip install --upgrade pip

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli

      # Install linter for CloudFormation template
      - pip install cfn-lint

      # Install cfn-nag
      - gem install cfn-nag

      # Install requirements
      - pip install -r lambda_functions/requirements.txt --target lambda_functions
      - pip install -r lambda_functions/requirements_layers.txt --target package/python

      # Install statelint to verify the validity of the state machine definition
      - gem install statelint

  pre_build:
    commands:
      # verify the validity of the state machine definition
      - statelint ./lambda_functions/stepfunctions/SearchFactChecks.asl.json
      # create template for stepfunction and add it to template.yaml
      - python ./lambda_functions/submission_service/stepfunctions/template_statemachine_cf.py --smdef ./lambda_functions/submission_service/stepfunctions/SearchFactChecks.asl.json --intemplate ./lambda_functions/submission_service/submission_service_template.yaml --outtemplate ./lambda_functions/submission_service/submission_service_template.yaml
      - cfn-lint -t ./lambda_functions/template.yaml
      - cfn_nag_scan -i ./lambda_functions -t template.yaml
      # Discover and run unit tests in the 'tests' directory. For more information, see <https://docs.python.org/3/library/unittest.html#test-discovery>
      # - python -m unittest discover lambda_functions/tests

  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - sed -i 's/VAR_HOSTEDZONEID/$HOSTEDZONEID/g;s/VAR_CERTARN/$CERTARN/g' ${STAGE}-config.json
      - aws cloudformation package --template-file ./lambda_functions/template.yaml --s3-bucket $S3_BUCKET --output-template-file ${STAGE}-template-export.yml

      # Do not remove this statement. This command is required for AWS CodeStar projects.
      # Update the AWS Partition, AWS Region, account ID and project ID in the project ARN on template-configuration.json file so AWS CloudFormation can tag project resources.

artifacts:
  files:
    - ${STAGE}-template-export.yml
    - ${STAGE}-config.json
    # - template-configuration.json
