"""Removed ReviewInProgress Table

Revision ID: 1c7d0ba8060d
Revises: d252ecbfc47a
Create Date: 2020-10-12 17:17:24.434245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c7d0ba8060d'
down_revision = 'd252ecbfc47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_in_progress')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews_in_progress',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('item_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('start_timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('is_peer_review', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name='reviews_in_progress_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reviews_in_progress_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
