"""Answer Options added

Revision ID: 6b4e36091047
Revises: cedce8eb10ad
Create Date: 2020-10-03 17:09:32.796023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4e36091047'
down_revision = 'cedce8eb10ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    options = op.create_table('answer_options',
                              sa.Column('id', sa.String(
                                  length=36), nullable=False),
                              sa.Column('text', sa.Text(), nullable=True),
                              sa.Column('value', sa.Integer(), nullable=True),
                              sa.PrimaryKeyConstraint('id')
                              )
    pairs = op.create_table('question_option_pairs',
                            sa.Column('question_id', sa.String(
                                length=36), nullable=True),
                            sa.Column('option_id', sa.Integer(),
                                      nullable=True),
                            sa.ForeignKeyConstraint(
                                ['option_id'], ['answer_options.id'], ),
                            sa.ForeignKeyConstraint(
                                ['question_id'], ['review_questions.id'], )
                            )
    op.drop_constraint('review_answers_ibfk_2',
                       'review_answers', type_='foreignkey')
    op.create_foreign_key(None, 'review_answers', 'review_questions', [
                          'review_question_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###

    # Update ids of review_questions
    op.execute('UPDATE review_questions SET id = "1a" WHERE id = "2"')
    op.execute('UPDATE review_questions SET id = "1b" WHERE id = "3"')
    op.execute('UPDATE review_questions SET id = "2" WHERE id = "4"')
    op.execute('UPDATE review_questions SET id = "3" WHERE id = "5"')
    op.execute('UPDATE review_questions SET id = "4" WHERE id = "6"')
    op.execute('UPDATE review_questions SET id = "5" WHERE id = "7"')
    op.execute('UPDATE review_questions SET id = "6" WHERE id = "8"')
    op.execute('UPDATE review_questions SET id = "7" WHERE id = "9"')
    op.execute('UPDATE review_questions SET id = "7a" WHERE id = "10"')
    op.execute('UPDATE review_questions SET id = "7b" WHERE id = "11"')
    op.execute('UPDATE review_questions SET id = "8" WHERE id = "12"')
    op.execute('UPDATE review_questions SET id = "9" WHERE id = "13"')

    # Insert answer options
    op.bulk_insert(options,
                   [
                       {
                           'id': '1',
                           'text': 'Stimme nicht zu',
                           'value': 1
                       },
                       {
                           'id': '2',
                           'text': 'Stimme eher nicht zu',
                           'value': 2
                       },
                       {
                           'id': '3',
                           'text': 'Stimme eher zu',
                           'value': 3
                       },
                       {
                           'id': '4',
                           'text': 'Stimme zu',
                           'value': 4
                       },
                       {
                           'id': 'Source0',
                           'text': 'Quellenangaben nicht erforderlich',
                           'value': 0
                       },
                       {
                           'id': 'Source1',
                           'text': 'Ausreichende Quellen nicht gefunden',
                           'value': 1
                       },
                       {
                           'id': 'NotRelevant0',
                           'text': 'Kriterium hier nicht zutreffend',
                           'value': 0
                       },
                       {
                           'id': 'Coverage1',
                           'text': 'Keine Berichterstattung gefunden',
                           'value': 1
                       },
                       {
                           'id': 'Citation1',
                           'text': 'Es werden keine Zitate verwendet',
                           'value': 1
                       },
                       {
                           'id': 'NotApplicable0',
                           'text': 'Nicht beurteilbar',
                           'value': 0
                       },

                   ]
                   )

    question_ids = ['1', '1a', '1b', '2', '3',
                    '4', '5', '6', '7', '7a', '7b', '8', '9']
    # For each question, insert standard options
    for qid in question_ids:
        op.bulk_insert(pairs,
                       [
                           {
                               'option_id': '1',
                               'question_id': qid,
                           },
                           {
                               'option_id': '2',
                               'question_id': qid,
                           },
                           {
                               'option_id': '3',
                               'question_id': qid,
                           },
                           {
                               'option_id': '4',
                               'question_id': qid,
                           }
                       ]
                       )
    # Insert 5th answer options where needed
    op.bulk_insert(pairs,
                   [
                       {
                           'option_id': 'Source0',
                           'question_id': '1',
                       },
                       {
                           'option_id': 'Source1',
                           'question_id': '1b',
                       },
                       {
                           'option_id': 'NotRelevant0',
                           'question_id': '3',
                       },
                       {
                           'option_id': 'NotRelevant0',
                           'question_id': '4',
                       },
                       {
                           'option_id': 'NotRelevant0',
                           'question_id': '5',
                       },
                       {
                           'option_id': 'Coverage1',
                           'question_id': '6',
                       },
                       {
                           'option_id': 'Citation1',
                           'question_id': '7',
                       },
                       {
                           'option_id': 'NotRelevant0',
                           'question_id': '8',
                       },
                       {
                           'option_id': 'NotApplicable0',
                           'question_id': '9',
                       }
                   ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_answers', type_='foreignkey')
    op.create_foreign_key('review_answers_ibfk_2', 'review_answers',
                          'review_questions', ['review_question_id'], ['id'])
    op.drop_table('question_option_pairs')
    op.drop_table('answer_options')
    # ### end Alembic commands ###
