"""Added item type column

Revision ID: d252ecbfc47a
Revises: 6b4e36091047
Create Date: 2020-10-09 11:28:44.910887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd252ecbfc47a'
down_revision = '6b4e36091047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('type', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'type')
    # ### end Alembic commands ###
