AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for the DetektivKollektiv submission API" # Change for each template

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  STAGE:
    Type: String
  CorsAllowOrigin:
    Type: String
  DBNAME:
    Type: String
    Default: development_db
  HOSTEDZONEID:
    Type: String
  CERTARN:
    Type: String

Conditions:
  IsProdEnvironment: !Equals [!Sub "${STAGE}", prod]

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: STAGE
      Cors:
        AllowMethods: "'OPTIONS, PUT, POST, GET, DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: AWS_IAM
        AddDefaultAuthorizerToCorsPreflight: false
        InvokeRole: NONE
      # Domain:
      #   DomainName:
      #     !If [
      #       IsProdEnvironment,
      #       submission-api.detektivkollektiv.org,
      #       !Sub "submission-api.${STAGE}.detektivkollektiv.org",
      #     ]
      #   CertificateArn: !Sub "${CERTARN}"
      #   EndpointConfiguration: EDGE
      #   Route53:
      #     HostedZoneId: !Sub "${HOSTEDZONEID}"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "detektivkollektiv-submission_api-execution-submission-service-${STAGE}" # Change for each Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute

  SubmitItemFunction: # Change for each lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-submission_api-submit-item-${STAGE}" # Change for each lambda
      CodeUri: .
      Handler: submit_item.submit_item # Change for each lambda
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Tracing: Active
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items # Change for each lambda
            Method: post # Change for each lambda
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
          CORS_ALLOW_ORIGIN:
            Ref: CorsAllowOrigin
      Layers:
        - Fn::ImportValue: !Sub "core-layer-arn-${STAGE}"
