AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for the DetektivKollektiv ml API" # Change for each template

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  STAGE:
    Type: String
  CorsAllowOrigin:
    Type: String
  DBNAME:
    Type: String
    Default: development_db

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: STAGE
      Cors:
        AllowMethods: "'OPTIONS, PUT, POST, GET, DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: AWS_IAM
        AddDefaultAuthorizerToCorsPreflight: false
        InvokeRole: NONE

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "detektivkollektiv-api-execution-ml-service-${STAGE}" # Change for each Role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/ComprehendFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess         

  GetFactcheckByItemidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-get_factcheck_by_itemid-${STAGE}"
      CodeUri: .
      Handler: get_online_factcheck.get_online_factcheck
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/{item_id}/factcheck
            Method: get
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
          CORS_ALLOW_ORIGIN:
            Ref: CorsAllowOrigin
          STAGE:
            Ref: STAGE

  SearchFactChecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-SearchFactChecks-${STAGE}"
      CodeUri: .
      Handler: SearchFactChecks.get_FactChecks
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-ml-requirements-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          STAGE:
            Ref: STAGE

  UpdateFactCheckModelsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-UpdateFactcheckModels-${STAGE}"
      CodeUri: .
      Handler: UpdateFactChecks.update_factcheck_models
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-ml-requirements-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          STAGE:
            Ref: STAGE

  GetLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-GetLanguage-${STAGE}"
      CodeUri: .
      Handler: GetLanguage.get_language
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetKeyPhrasesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-GetKeyPhrases-${STAGE}"
      CodeUri: .
      Handler: GetKeyPhrases.get_phrases
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetEntitiesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-GetEntities-${STAGE}"
      CodeUri: .
      Handler: GetEntities.get_entities
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetTagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-GetTags-${STAGE}"
      CodeUri: .
      Handler: GetEntities.get_tags
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetTagsByItemidFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-get_tags_by_itemid-${STAGE}"
      CodeUri: .
      Handler: GetTags.get_tags_for_item
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        Echo:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /items/{item_id}/tags
            Method: get
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
          CORS_ALLOW_ORIGIN:
            Ref: CorsAllowOrigin
        
  ExtractClaimFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-ExtractClaim-${STAGE}"
      CodeUri: .
      Handler: ExtractClaim.extract_claim
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-ml-requirements-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  GetSentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-GetSentiment-${STAGE}"
      CodeUri: .
      Handler: GetSentiment.get_sentiment
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn

  UpdateLanguageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-UpdateItem-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.update_item
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreFactChecksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreFactChecks-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_factchecks
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreItemURL:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreItemURL-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_itemurl
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreItemEntityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreItemEntities-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_itementities
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreItemTagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreItemTags-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_itemtags
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreItemSentimentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreItemSentiment-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_itemsentiment
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME

  StoreItemKeyphraseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-ml_api-StoreItemKeyphrases-${STAGE}"
      CodeUri: .
      Handler: EnrichItem.store_itemphrases
      Runtime: python3.8
      MemorySize: 832
      Layers:
        - arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-dev:1
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
