AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "SAM template for the DetektivKollektiv admin API"

Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.1

Parameters:
  STAGE:
    Type: String
  CorsAllowOrigin:
    Type: String
  DBNAME:
    Type: String
    Default: development_db

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName:
        Ref: STAGE
      Cors:
        AllowMethods: "'OPTIONS, PUT, POST, GET, DELETE'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: AWS_IAM
        AddDefaultAuthorizerToCorsPreflight: false
        InvokeRole: NONE

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "detektivkollektiv-api-execution-admin-service-${STAGE}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonRDSDataFullAccess
        - arn:aws:iam::aws:policy/SecretsManagerReadWrite
        - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess

  UpdateItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-admin_api-update_item-${STAGE}"
      CodeUri: .
      Handler: update_item.update_item
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Tracing: Active
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items/{item_id}
            Method: put
            RestApiId:
              Ref: Api
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
          CORS_ALLOW_ORIGIN:
            Ref: CorsAllowOrigin
      Layers:
        - !Sub "arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-${STAGE}:1"

  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "detektivkollektiv-admin_api-get_items-${STAGE}"
      CodeUri: .
      Handler: get_items.get_items
      Runtime: python3.8
      MemorySize: 832
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Tracing: Active
      Events:
        Echo:
          Type: Api
          Properties:
            Path: /items
            Method: get
            RestApiId:
              Ref: Api
            RequestParameters:
              - method.request.querystring.status:
                  Required: false
                  Caching: false
              - method.request.querystring.language:
                  Required: false
                  Caching: false
      Environment:
        Variables:
          DBNAME:
            Ref: DBNAME
          CORS_ALLOW_ORIGIN:
            Ref: CorsAllowOrigin
      Layers:
        - !Sub "arn:aws:lambda:eu-central-1:891514678401:layer:detektivkollektiv-core-layer-${STAGE}:1"
